name: Rubeus-Build

on: [push]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Release]
    
    steps:
         
      - uses: actions/checkout@v1
      
      - name: Build Rubeus
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\Seatbelt\Seatbelt.csproj  
           
      - uses: actions/upload-artifact@master
        with:
          name: Rubeus
          path: Rubeus\bin\Release\Rubeus.exe 
