name: Rubeus-Build

on: [push]
jobs:
  build:
    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v1
      
      - name: install obfuscar
        run: dotnet tool install --global Obfuscar.GlobalTool --version 2.2.26
        
      - name: Build Rubeus
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe /p:Configuration=Release $Env:GITHUB_WORKSPACE\Rubeus\Rubeus.csproj       
     
      - name: Invoke Obfuscar
        run: obfuscar.console.exe $Env:GITHUB_WORKSPACE\Rubeus\obfuscar.xml 
           
      - uses: actions/upload-artifact@master
        with:
          name: Rubeus
          path: Rubeus\bin\Release\Rubeus.exe
          
      - uses: actions/upload-artifact@master
        with:
          name: Rubeus_Obfuscar
          path: Rubeus\bin\Release\Obfuscar\SpicyRub.exe
